# Set environment variables for Azure access

export CLIENT_ID=...
export PASSWORD=...
export TENANT=...
export SUBSCRIPTION=...

# Optionally install Azure CLI if not present already
# curl -L https://aka.ms/InstallAzureCli | bash

